name: CI

on: [pull_request]

jobs:
  build:
    name: CI/CD
    runs-on: macos-latest
    strategy:
      matrix:
        destinations: ['platform=iOS Simulator,OS=13.3,name=iPhone 11', 'platform=tvOS Simulator,OS=13.3,name=Apple TV 4K']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate Xcode Project
      run: swift package generate-xcodeproj
    - name: Build and Test
      run: xcodebuild clean test -destination "${destination}" -scheme 'BarcodeView-Package' ONLY_ACTIVE_ARCH=NO
      env: 
       destination: ${{ matrix.destination }}
      
